### ISSUE TITLE
Add favicons in their own folder

### ISSUE THREAD

**Issue by youngchief-btw** [khalby786/khalby786.github.io#2]
I know what you might be thinking... the website I used to make these awesome favicons told me to so leave them in the root.

Actually it will still work, you just need to edit the spots where you link to them to add the folder, I have tried it myself and it works.

**Comment by khalby786** [comment]
Hey @youngchief-btw,

1. I prefer to add the favicons in the root directory, and they're much easier to refer to.
2. Again, the contents of the GitHub repo is actually a `public` folder generated from different values and parameters using Gatsby. So editing the structure might break the build.
